### ISSUE TITLE
naive ui如何不在setup里使用ts代码打开信息、通知等组件

### ISSUE THREAD

**Issue by CS-liujf** [markthree/tov-template-with-naive-ui#1]
大佬你好，我是昨天在b站询问你的粉丝
由于我对vue不是很熟悉，所以现在遇到了一个问题不知道该如何解决。我以前用vue2时，用的是element ui，他的消息(信息)组件可以使用` this.$message('这是一条消息提示')` 来打开，因此我可以在我的request.js(封装了请求响应拦截器)里直接通过代码打开消息组件，但是naive ui似乎没有直接提供这个全局方法，那么我该如何处理达到同样的效果？我看了naive ui的官网，它的确有说可以挂载到window上，这样就不需要在setup中去调用，但是我不太明白该如何操作，即我的App.vue该如何书写，因为App.vue里要用router-view这个组件

**Comment by markthree** [comment]
或许我可以让它变成全局的

**Comment by CS-liujf** [comment]
> 或许我可以让它变成全局的

其实我并没有用你的模板😂，是我自己搭建的时候遇到了这个问题，不过很荣幸能够被打上feature tag

**Comment by markthree** [comment]
@CS-liujf 靓仔你好，因为 `naive-ui` 为了更好的支持 `ssr`，所以内部应该采用了 `provide` 和 `inject` 来写。
这意味着全局挂载时一定需要有中间的顶层组件来接收 `inject` 出来的 `message` 实例。

我的做法比较简单粗暴，直接做了个中间层 `message` 组件。具体可见最新提交 [src/components/message.vue](https://github.com/markthree/tov-template-with-naive-ui/blob/main/src/components/message.vue)
和 [src/App.vue](https://github.com/markthree/tov-template-with-naive-ui/blob/main/src/App.vue)，至于类型的声明可以在你的环境类型声明 `.d.ts` 文件里补充 👇
 ```ts
import type { MessageProviderInst } from 'naive-ui'

// 挂载到 windows 上
declare global {
	interface Window {
		$message: MessageProviderInst
	}
}
```
具体可见 👉 [presets/types/env.d.ts](https://github.com/markthree/tov-template-with-naive-ui/blob/main/presets/types/env.d.ts)

**Comment by markthree** [comment]
当然这种做法可能需要用户做过多的操作，后续我可能会做成一个开箱即用的 `vite` 插件，让全局的通知更简单

**Comment by CS-liujf** [comment]
> @CS-liujf 靓仔你好，因为 `naive-ui` 为了更好的支持 `ssr`，所以内部应该采用了 `provide` 和 `inject` 来写。 这意味着全局挂载时一定需要有中间的顶层组件来接收 `inject` 出来的 `message` 实例。
> 
> 我的做法比较简单粗暴，直接做了个中间层 `message` 组件。具体可见最新提交 [src/components/message.vue](https://github.com/markthree/tov-template-with-naive-ui/blob/main/src/components/message.vue) 和 [src/App.vue](https://github.com/markthree/tov-template-with-naive-ui/blob/main/src/App.vue)，至于类型的声明可以在你的环境类型声明 `.d.ts` 文件里补充 👇
> 
> ```ts
> import type { MessageProviderInst } from 'naive-ui'
> 
> // 挂载到 windows 上
> declare global {
>    interface Window {
>    	$message: MessageProviderInst
>    }
> }
> ```
> 
> 具体可见 👉 [presets/types/env.d.ts](https://github.com/markthree/tov-template-with-naive-ui/blob/main/presets/types/env.d.ts)

原来如此，谢谢讲解，我第一次遇见这样的写法，所以当时觉得naive ui不是很方便，没想到它是出于这样的考量。我看了一下，naive的 对话框、通知、信息组件都是如此设计的，如果你要开发vite插件，可否把另外俩组件也一并囊括了？

**Comment by markthree** [comment]
应该可以

**Comment by markthree** [comment]
@CS-liujf 靓仔你好，`vite` 面向组件库的全局 `api` 的插件已完成，具体可见 👉 [vite-plugin-global-api](https://github.com/dishait/vite-plugin-global-api)

**Comment by CS-liujf** [comment]
ok，谢谢提醒
