### ISSUE TITLE
如何实现全局点击切换夜间模式

### ISSUE THREAD

**Issue by CS-liujf** [markthree/tov-template-with-naive-ui#2]
我看到你是通过调用toggleDark来实现点击切换成夜间模式，但由于你是采用自动引入的方式，我没法查看到toggleDark的具体实现😂。由于`<n-config-provider :theme="theme">` 是在App.Vue中，而我的切换按钮是在其他组件里，我很好奇该如何实现点击切换夜间/白天模式，是否需要用到全局状态管理如pinia？主要我对vue并不怎么了解😭

**Comment by markthree** [comment]
这种情况只能上全局的响应式状态管理，当然你可以用 `pinia`，`vuex`，或者自己手动写一个。如果是非常轻的应用也可以用 `event bus` [mitt](https://github.com/developit/mitt)

**Comment by markthree** [comment]
如果不考虑 `SSR` 的话，我个人更倾向直接写个简单的 `composition-api`。

以下是一个简单的示例，当然如果你希望看懂他们，还是仍然要系统学习下 `vue3` 😂

```ts
// src/composables/useTheme
import { ref, computed } from 'vue'
import { darkTheme, useOsTheme } from 'naive-ui'

export const osTheme = useOsTheme()

export const isDark = ref(osTheme.value === 'dark')

export const theme = computed(() => {
  return isDark.value ? darkTheme : null
})

export const toggleTheme = (status = !isDark.value) => {
  isDark.value = status
}
```

```html
// src/App.vue
<script setup lang="ts">
import { computed } from 'vue'
import { isDark, theme } from './composables/useTheme'

const themeClass = computed(() => isDark.value ? 'light' : 'dark')
</script>

<template>
  <n-config-provider :theme="theme" :class="themeClass">
    <router-view />
  </n-config-provider>
</template>

<style>
#app > .n-config-provider {
  height: 100vh;
  transition: background-color 0.2s ease-in-out;
}

.dark {
  color: #adbac7;
  background-color: #22272e;
}
</style>
```

```html
// src/pages/Home.vue
<script setup lang="ts">
  import { computed } from 'vue'
  import {
    isDark,
    toggleTheme
  } from '../composables/useTheme'
  
  const message = computed(() => {
    return isDark.value ? 'to light' : 'to dark'
  })
</script>

<template>
  <div class="home">
    <n-button @click="toggleTheme()"> {{ message }} </n-button>
  </div>
</template>

<style>
  .home {
    display: flex;
    align-items: center;
    justify-content: center;
    height: 60vh;
  }
</style>
```

**Comment by CS-liujf** [comment]
> 如果不考虑 `SSR` 的话，我个人更倾向直接写个简单的 `composition-api`。
> 
> 以下是一个简单的示例，当然如果你希望看懂他们，还是仍然要系统学习下 `vue3` 😂
> 
> ```ts
> // src/composables/useTheme
> import { ref, computed } from 'vue'
> import { darkTheme, useOsTheme } from 'naive-ui'
> 
> export const osTheme = useOsTheme()
> 
> export const isDark = ref(osTheme.value === 'dark')
> 
> export const theme = computed(() => {
> 	return isDark.value ? darkTheme : null
> })
> 
> export const toggleTheme = (status = !isDark.value) => {
> 	isDark.value = status
> }
> ```
> 
> ```
> // src/App.vue
> <script setup lang="ts">
> 	import { computed } from 'vue'
> 	import { isDark, theme } from './composables/useTheme'
> 
> 	const themeClass = computed(() =>
> 		isDark.value ? 'light' : 'dark'
> 	)
> </script>
> 
> <template>
> 	<n-config-provider :theme="theme" :class="themeClass">
> 		<router-view />
> 	</n-config-provider>
> </template>
> 
> <style>
> 	#app > .n-config-provider {
> 		height: 100vh;
> 		transition: background-color 0.2s ease-in-out;
> 	}
> 
> 	.dark {
> 		color: #adbac7;
> 		background-color: #22272e;
> 	}
> </style>
> ```
> 
> ```
> // src/pages/Home.vue
> <script setup lang="ts">
> 	import { computed } from 'vue'
> 	import {
> 		isDark,
> 		toggleTheme
> 	} from '../composables/useTheme'
> 
> 	const message = computed(() => {
> 		return isDark.value ? 'to light' : 'to dark'
> 	})
> </script>
> 
> <template>
> 	<div class="home">
> 		<n-button @click="toggleTheme()">
> 			{{ message }}
> 		</n-button>
> 	</div>
> </template>
> 
> <style>
> 	.home {
> 		display: flex;
> 		align-items: center;
> 		justify-content: center;
> 		height: 60vh;
> 	}
> </style>
> ```

谢谢你的耐心解答，我的确不需要考虑ssr。我仔细研究研究

**Comment by CS-liujf** [comment]
真的太感谢啦，你提供的这个示例让我豁然开朗，我原先思维仅停留在全局状态管理上，没有想到利用vue3的ref等函数

**Comment by markthree** [comment]
@CS-liujf 不客气的

**Comment by CS-liujf** [comment]
请问为什么此时不是响应式的

```vue

<script setup lang="ts">
	import {isDark,toggleTheme} from '../composables/useTheme'
</script>

<template>
	<div v-if="isDark.value" @click="toggleTheme()">to light</div>
        <button v-else @click="toggleTheme()">to dark </button>
</template>

```

如果我想用v-if，似乎得对`isDark.value`包裹上computed，那么更优雅的方式应该是什么？谢谢

**Comment by markthree** [comment]
> 请问为什么此时不是响应式的
> 
> ```
> <script setup lang="ts">
> 	import {isDark,toggleTheme} from '../composables/useTheme'
> </script>
> 
> <template>
> 	<div v-if="isDark.value" @click="toggleTheme()">to light</div>
>         <button v-else @click="toggleTheme()">to dark </button>
> </template>
> ```
> 
> 如果我想用v-if，似乎得对`isDark.value`包裹上computed，那么更优雅的方式应该是什么？谢谢

为啥要在模板里使用 `isDark.value` 访问呢？直接 `isDark` 访问即可拿到对应的响应式量。

```html
<script setup lang="ts">
import { isDark,toggleTheme } from '../composables/useTheme'
</script>

<template>
    <div v-if="isDark" @click="toggleTheme()">to light</div>
    <button v-else @click="toggleTheme()">to dark </button>
</template>
```
另外也不推荐在能复用的情况下使用 `v-if`，用计算属性可以得到最好的性能 👇
```html
<script setup lang="ts">
import { computed } from 'vue'
import { isDark,toggleTheme } from '../composables/useTheme'

const msg = computed(() => isDark.value ? 'to dark' : 'to light')
</script>

<template>
      <button @click="toggleTheme()">{{msg}}</button>
</template>
```
最后仍然还是推荐你过一遍文档系统的了解下 `vue` 再进行后续的开发，👉 [staging-cn.vuejs.org](https://staging-cn.vuejs.org/)

**Comment by CS-liujf** [comment]
好的好的，我一定去过一遍文档。另外为什么我要用v-if，这是由于根据isDark值的不同显示不同的html标签
