### ISSUE TITLE
关于naive ui表格的使用

### ISSUE THREAD

**Issue by CS-liujf** [markthree/tov-template-with-naive-ui#3]
你好，navie ui的表格得直接使用h函数才能完成单元格内的组件，比如官网的例子https://github.com/tusen-ai/naive-ui/blob/4c0ee46f22a84216ede6c6f3f6bf24dbf7745838/src/data-table/demos/zhCN/basic.demo.vue#L47

请问有什么封装的方法可以改成直接在template里通过slot来完成？我能想到的一个近似解是用tsx/jsx来写，那么是否有其他方法。

**Comment by markthree** [comment]
@CS-liujf 靓仔你好，我对此并没有太多的研究，你可以去 [naive-ui/issues](https://github.com/tusen-ai/naive-ui/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) 问问
